# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
addons:
  apt:
    packages:
      - libudunits2-dev
cache: packages
r: release
r_github_packages:
  - r-lib/covr
  - jimhester/lintr

after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
